field: 555efa28-a6b9-471d-8548-735eae07cb3c
fieldLayouts:
  b2bdbd9c-8a57-4737-acb9-78ab2b12bab8:
    tabs:
      -
        fields:
          0accbbf3-3501-4536-b0f0-19facda9bb98:
            required: true
            sortOrder: 1
          107df6dd-7f1a-4575-811d-ae34d2258fd8:
            required: true
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  0accbbf3-3501-4536-b0f0-19facda9bb98:
    contentColumnType: text
    fieldGroup: null
    handle: numberTitle
    instructions: 'What specific organization/person/place is this number going to?'
    name: 'Number Title'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  107df6dd-7f1a-4575-811d-ae34d2258fd8:
    contentColumnType: text
    fieldGroup: null
    handle: number
    instructions: ''
    name: Number
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: other
name: Other
sortOrder: 4
