field: 5ff206fa-fc15-4726-a9e2-0ed8b6da6407
fieldLayouts:
  ec6de2e7-73ca-492e-ae67-0ccb0b7e86eb:
    tabs:
      -
        elements:
          -
            fieldUid: 8bd35022-d988-494a-9395-34bb21d37c18
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a8865a0e-a230-4411-902e-53af47982f47
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d103112-5444-4b00-aefb-95f9d113a8a2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 91c73b27-40c7-4fb9-b63e-fecb57ed61ec
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 236ba3eb-c1d3-4cb0-a2e5-f340dbf38399
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  236ba3eb-c1d3-4cb0-a2e5-f340dbf38399:
    contentColumnType: text
    fieldGroup: null
    handle: phoneNumber
    instructions: 'Adds a custom phone number for this person'
    name: 'Phone Number'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4d103112-5444-4b00-aefb-95f9d113a8a2:
    contentColumnType: text
    fieldGroup: null
    handle: officeDepartment
    instructions: 'Adds a custom office or department title for this person'
    name: Office/Department
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8bd35022-d988-494a-9395-34bb21d37c18:
    contentColumnType: string
    fieldGroup: null
    handle: person
    instructions: ''
    name: Person
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add an official'
      showSiteMenu: true
      source: null
      sources:
        - 'section:28881fc8-3e61-4fdb-a5ee-cce1bab725bf'
        - 'section:07faad04-9ec4-4f68-9fe8-0ca20f189f8a'
      targetSiteId: null
      validateRelatedElements: true
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  91c73b27-40c7-4fb9-b63e-fecb57ed61ec:
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: 'Adds a custom email address for this person'
    name: Email
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a8865a0e-a230-4411-902e-53af47982f47:
    contentColumnType: text
    fieldGroup: null
    handle: jobTitle
    instructions: 'Adds a custom job title override for this person'
    name: 'Job Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: person
name: Person
sortOrder: 1
