fieldLayouts:
  d8bfc1d3-a266-4f51-bb19-f3acab14edaa:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: f62c85ae-2203-4d1a-8702-da515126a398
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c2ad07dc-05e7-4ef4-89b6-2e1eaccee210
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bef74be8-b22d-4dd0-9217-9707bb43d888
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9eb69e7e-c32d-4390-9b2e-ce2344718906
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6036ab26-c74a-4a0e-95f8-1735e64eed98
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 48c765be-2eab-42d5-bb78-461b32ba7d6a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 655e742b-956c-4fc9-b241-b913e5b814d7
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bae021eb-4222-44c0-adb5-05e045cca640
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5d92130f-648c-4519-ad6d-f68508ca2a2f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 415c75c4-9891-451d-b333-be4acb59c1fd
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 7d16fac3-b66a-4185-9f2e-d4cac77b58d5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e1a1763e-027e-46b1-86b6-e115fc43f064
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4060bfe6-8574-4b8f-bb64-ea670ce40748
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5ff206fa-fc15-4726-a9e2-0ed8b6da6407
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5e60d793-558b-4747-8c69-8c91c1a3102b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fbc5e95d-0c99-4d55-8eb5-a2156eac9c1d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fccfab94-5755-4a9a-96e5-9ed8359b99f4
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 229564d1-ebbb-4cc3-9ff1-37466e51fae5
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Media Center'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: ecc31df6-640f-4fa6-a2e6-caea757e379d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 3
handle: aboutOakland
hasTitleField: false
name: 'About Oakland'
section: 3bcee420-a923-4de2-9e6c-9081062b06e1
sortOrder: 1
titleFormat: '{section.name|raw}'
