fieldLayouts:
  7c52f103-aea0-40ed-a9e2-8b6ede36af20:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: c2ad07dc-05e7-4ef4-89b6-2e1eaccee210
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f62c85ae-2203-4d1a-8702-da515126a398
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bef74be8-b22d-4dd0-9217-9707bb43d888
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ecc31df6-640f-4fa6-a2e6-caea757e379d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: eventsIndex
hasTitleField: true
name: 'Events Index'
section: 9a9e5725-12f9-4f36-81cc-7762a4912de0
sortOrder: 1
titleFormat: null
