fieldLayouts:
  e0dfa110-8bb7-42a8-8f3a-4b991b4740c3:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: f62c85ae-2203-4d1a-8702-da515126a398
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c2ad07dc-05e7-4ef4-89b6-2e1eaccee210
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bef74be8-b22d-4dd0-9217-9707bb43d888
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5ff206fa-fc15-4726-a9e2-0ed8b6da6407
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7d16fac3-b66a-4185-9f2e-d4cac77b58d5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e1a1763e-027e-46b1-86b6-e115fc43f064
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4060bfe6-8574-4b8f-bb64-ea670ce40748
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fbc5e95d-0c99-4d55-8eb5-a2156eac9c1d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fccfab94-5755-4a9a-96e5-9ed8359b99f4
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 229564d1-ebbb-4cc3-9ff1-37466e51fae5
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ecc31df6-640f-4fa6-a2e6-caea757e379d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: mediaCenter
hasTitleField: false
name: 'Media Center'
section: 36d0160d-50c5-479d-8efc-5959cb5bd45a
sortOrder: 1
titleFormat: '{section.name|raw}'
