fieldLayouts:
  83afe219-77cd-482e-99ac-4397f9e8a180:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: ea2bc4af-23f2-4838-99c2-9da78c63420f
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 842891f1-23fb-4af0-93b5-d197738f08a0
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5e5aad16-6bdc-4d3e-adfd-75147a323b78
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2fb76e53-8619-4e29-b609-c984c390de9a
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: mediaContact
hasTitleField: false
name: 'Media Contact'
section: 4c69249e-8905-4924-88d0-4eaa4ce13edc
sortOrder: 1
titleFormat: '{role} - {staffEntry.one.title}'
