fieldLayouts:
  2f92e1ba-0a2f-4fd8-a04f-b5e45b8aa96f:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: f62c85ae-2203-4d1a-8702-da515126a398
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c2ad07dc-05e7-4ef4-89b6-2e1eaccee210
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bef74be8-b22d-4dd0-9217-9707bb43d888
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fd0c8e02-99b4-4ce5-ab89-b29cd0efc581
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ecc31df6-640f-4fa6-a2e6-caea757e379d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: oaklandHomelessResponse
hasTitleField: true
name: 'Oakland Homeless Response'
section: 3d20db52-3ddf-4e65-baee-9e51e72240a3
sortOrder: 1
titleFormat: ''
