fieldLayouts:
  60190c44-7789-43e6-a223-27d3243ad638:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: e6b42dcc-e049-437d-b803-c75b6f95e6af
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 16a8d87b-63fc-4df3-8597-2d70c5a4f987
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fd0c8e02-99b4-4ce5-ab89-b29cd0efc581
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 984d9094-e92b-4a6f-966a-e7c21159f950
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ecc31df6-640f-4fa6-a2e6-caea757e379d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: pressReleases
hasTitleField: true
name: 'Press Releases'
section: 542c176a-f523-4bf7-a1bd-8536d79682c9
sortOrder: 1
titleFormat: ''
