fieldLayouts:
  bc2507db-b195-40e3-937b-f39a0a0f4cfb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: b9f7ae6c-d494-4169-802f-32d4e1659a1c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 41e64e96-658b-4686-a45e-876808b04da6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8a298708-bd62-4f5d-b277-e76e6c2f6041
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f5ec8d7-c11e-43a0-9bae-82709ddffe49
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b63ff443-ed3d-489e-b84a-b410aa3e09cd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0ed51bfe-acce-4e07-8017-8b3498bcba94
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 044231f1-5e15-4ab5-bb69-e8afeb4d908d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d14c3f65-a312-48e0-a7e6-52cdbf5632ef
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eac17a7e-9cb8-464b-9a5e-2f0342162433
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: redistrictingCommissionApplication
hasTitleField: false
name: 'Redistricting Commission Application'
section: 9168f154-c0f9-4cf9-991d-60b287a85fc0
sortOrder: 2
titleFormat: '{applicantName} - {district}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
