fieldLayouts:
  6bfec61f-f233-4b6d-8926-eebff6c16e28:
    tabs:
      -
        elements:
          -
            instructions: null
            label: APN
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 8ff1f216-9327-4d13-952e-f47f08febbfd
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 31d30a51-422e-471c-be55-3441a4219dd8
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: specialAssessmentTestStatus
hasTitleField: true
name: 'Special Assessment Test Status'
section: 9168f154-c0f9-4cf9-991d-60b287a85fc0
sortOrder: 3
titleFormat: ''
