fieldLayouts:
  f75e15d8-990c-474c-9777-ebb0ebc96fad:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: c2ad07dc-05e7-4ef4-89b6-2e1eaccee210
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f62c85ae-2203-4d1a-8702-da515126a398
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: bef74be8-b22d-4dd0-9217-9707bb43d888
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ecc31df6-640f-4fa6-a2e6-caea757e379d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: topicsIndex
hasTitleField: true
name: 'Topics Index'
section: 210f35e9-172e-4116-9382-05774c79d1ff
sortOrder: 1
titleFormat: null
