fieldLayouts:
  ec980d66-163d-4a97-be21-f1626a2370e4:
    tabs:
      -
        fields:
          fff5cf49-87e6-4751-9032-b4ca8136e237:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: headers
hasUrls: true
name: Headers
settings:
  autoFocalPoint: ''
  bucket: cao-94612
  bucketSelectionMode: choose
  cfDistributionId: ''
  cfPrefix: ''
  expires: ''
  keyId: $S3_API_KEY
  makeUploadsPublic: '1'
  region: us-west-2
  secret: $S3_SECRET
  storageClass: ''
  subfolder: headers
sortOrder: 5
type: craft\awss3\Volume
url: 'https://cao-94612.s3.amazonaws.com/'
