handle: pressReleaseFiles
hasUrls: true
name: 'Press Release Files'
settings:
  autoFocalPoint: ''
  bucket: cao-94612
  bucketSelectionMode: choose
  cfDistributionId: ''
  cfPrefix: ''
  expires: ''
  keyId: $S3_API_KEY
  makeUploadsPublic: '1'
  region: us-west-2
  secret: $S3_SECRET
  storageClass: ''
  subfolder: press-release-files
sortOrder: 14
type: craft\awss3\Volume
url: 'https://s3.us-west-2.amazonaws.com/cao-94612/'
