fieldLayouts:
  db8d627c-2a6c-45d7-bed9-1e889f21cb61:
    tabs:
      -
        fields:
          fff5cf49-87e6-4751-9032-b4ca8136e237:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: projects
hasUrls: true
name: Projects
settings:
  autoFocalPoint: ''
  bucket: cao-94612
  bucketSelectionMode: choose
  cfDistributionId: ''
  cfPrefix: ''
  expires: ''
  keyId: $S3_API_KEY
  makeUploadsPublic: '1'
  region: us-west-2
  secret: $S3_SECRET
  storageClass: ''
  subfolder: projects
sortOrder: 4
type: craft\awss3\Volume
url: 'https://cao-94612.s3.us-west-2.amazonaws.com'
