contentColumnType: text
fieldGroup: 27454cbc-e66b-4d88-bef3-32b87a69a715
handle: cityBudgetAndFinancialsSummary
instructions: ''
name: 'City Budget and Financials Summary'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: 'Basic with Links.json'
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
