contentColumnType: text
fieldGroup: 27454cbc-e66b-4d88-bef3-32b87a69a715
handle: cityProfile
instructions: ''
name: 'City Profile'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: '1'
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
