contentColumnType: string
fieldGroup: 8e8ee56e-cdb8-4206-a3b5-c3aa0eb3a884
handle: fundingLogos
instructions: 'Add logos for any funders that are involved with this project. They will be placed in a grid at the bottom of the page.'
name: 'Funding Logos'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:a31d23bf-e3ee-4942-95e0-3d14c29620bb'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add a logo'
  singleUploadLocationSource: 'volume:4494beaa-9c1f-44ae-b040-36f60f3d055d'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
