contentColumnType: text
fieldGroup: b1b0e0eb-fd37-4708-96c7-4f5f11d8fdb0
handle: groupHeadTitle
instructions: ''
name: 'Group Head Title'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
