contentColumnType: text
fieldGroup: b1b0e0eb-fd37-4708-96c7-4f5f11d8fdb0
handle: groupHeadBio
instructions: 'Write the bio for the lead. Try to keep the bio under 400 words.'
name: 'Group Head Bio'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: 'Simple with Links.json'
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
