contentColumnType: text
fieldGroup: 909c71fc-999c-4729-86d5-49cc9061f521
handle: leadIn
instructions: 'Enter the text that will appear under the banner. Remember to keep it short!'
name: 'Lead In'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
