contentColumnType: string
fieldGroup: 27454cbc-e66b-4d88-bef3-32b87a69a715
handle: mediaCenterLeadership
instructions: ''
name: 'Media Center Leadership'
searchable: true
settings:
  contentTable: '{{%matrixcontent_mediacenterleadership}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
