contentColumnType: string
fieldGroup: 27454cbc-e66b-4d88-bef3-32b87a69a715
handle: mediaContacts
instructions: ''
name: 'Media Contacts'
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add a contact'
  source: null
  sources:
    - 'section:4c69249e-8905-4924-88d0-4eaa4ce13edc'
  targetSiteId: null
  validateRelatedElements: '1'
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
