contentColumnType: string
fieldGroup: 83c14444-efcf-4d13-a20a-56275fd18855
handle: pageResources
instructions: 'Choose up to six (6) resources to show on this page.'
name: 'Page Resources'
searchable: true
settings:
  allowSelfRelations: false
  limit: '6'
  localizeRelations: false
  selectionLabel: 'Add a resource'
  showSiteMenu: true
  source: null
  sources:
    - 'section:24fa116b-8516-4626-84f3-86b685e71071'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
