contentColumnType: string
fieldGroup: 83c14444-efcf-4d13-a20a-56275fd18855
handle: pageProjects
instructions: 'Choose up to six (6) projects to show on this page.'
name: 'Page Projects'
searchable: true
settings:
  allowSelfRelations: false
  limit: '6'
  localizeRelations: false
  selectionLabel: 'Add a project'
  showSiteMenu: true
  source: null
  sources:
    - 'section:98d541ae-56ee-4c98-ba9c-37438dc485a0'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
