contentColumnType: string
fieldGroup: 83c14444-efcf-4d13-a20a-56275fd18855
handle: pageTopics
instructions: 'Choose up to six (6) topics to show on this page.'
name: 'Page Topics'
searchable: true
settings:
  limit: '6'
  localizeRelations: false
  selectionLabel: 'Add a topic'
  source: null
  sources:
    - 'section:70778563-6dac-453d-a4b0-5121f3a614b7'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
