contentColumnType: string
fieldGroup: 83c14444-efcf-4d13-a20a-56275fd18855
handle: pageServices
instructions: 'Choose up to six (6) services to show on the page.'
name: 'Page Services'
searchable: true
settings:
  allowSelfRelations: false
  limit: '6'
  localizeRelations: false
  selectionLabel: 'Add a service'
  showSiteMenu: true
  source: null
  sources:
    - 'section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
