contentColumnType: string
fieldGroup: 27454cbc-e66b-4d88-bef3-32b87a69a715
handle: pressReleaseImage
instructions: ''
name: 'Press Release Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:549d1a55-e94b-4c89-9cb9-b1fdac9d417d'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add a main image'
  singleUploadLocationSource: 'volume:10fea577-3555-45aa-9169-8e3dee085cae'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  validateRelatedElements: '1'
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
