contentColumnType: string
fieldGroup: 27454cbc-e66b-4d88-bef3-32b87a69a715
handle: quickFactsAtAGlance
instructions: ''
name: 'Quick Facts at a Glance'
searchable: false
settings:
  contentTable: '{{%matrixcontent_quickfactsataglance}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
