contentColumnType: string(255)
fieldGroup: 909c71fc-999c-4729-86d5-49cc9061f521
handle: redirectUrl
instructions: 'This is the URL that the page should redirect to.'
name: 'Redirect URL'
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
