contentColumnType: string
fieldGroup: 83c14444-efcf-4d13-a20a-56275fd18855
handle: resources
instructions: 'Choose the resource landing pages to relate to this entry.'
name: Resources
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add a resource'
  source: null
  sources:
    - 'section:24fa116b-8516-4626-84f3-86b685e71071'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
