contentColumnType: string
fieldGroup: 5bc46e53-a87c-4584-89aa-808cacedf461
handle: serviceTypes
instructions: ''
name: 'Service Types'
searchable: true
settings:
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: 'Add a type'
  source: 'group:8bcf4697-1dd2-47b2-91e2-8ad9b4b86741'
  sources: '*'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
