contentColumnType: text
fieldGroup: 71fb693f-011b-4669-ba10-f1b379557bb9
handle: staffImportPhoneNumber
instructions: ''
name: 'Staff Import Phone Number'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
