contentColumnType: string(255)
fieldGroup: 909c71fc-999c-4729-86d5-49cc9061f521
handle: videoLink
instructions: ''
name: 'Video Link'
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
