fieldLayouts:
  5a2d2246-c14b-4c8b-a973-cc070f30ce97:
    tabs:
      -
        fields:
          277068ba-95c5-4881-862f-85c19b60d4da:
            required: false
            sortOrder: 6
          36fcc9c4-85be-4bd9-959a-5b26e30673d4:
            required: false
            sortOrder: 3
          658cca3c-01d9-4de0-b0be-bc04b699d806:
            required: false
            sortOrder: 2
          6fb3f41c-93f6-4185-9622-e6765cdcc837:
            required: false
            sortOrder: 5
          7485ca3f-30b1-4ca6-a095-c2061d848559:
            required: false
            sortOrder: 1
          9c0b44a4-b6de-498e-bc9d-4f7a4f9fe5f2:
            required: false
            sortOrder: 4
        name: Content
        sortOrder: 1
handle: sitewideAlert
name: 'Sitewide Alert'
