enableVersioning: true
handle: pressReleasesIndex
name: 'Press Releases Index'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c35d3a93-d7f4-4c37-ae3e-1b4d403311bb:
    enabledByDefault: true
    hasUrls: true
    template: media-center/press-releases/index
    uriFormat: media-center/press-releases
type: single
